fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", --line-length=88]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--line-length=88, --exclude='/migrations/']
  - repo: https://github.com/myint/autoflake
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        args: ['--ignore=E203,W503', '--max-line-length=120']
        exclude: ^migrations/


