version: "3.8"
services:

  django: &django
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/var/static
    ports:
      - 80:8000
    env_file:
      - .env
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432

  celery:
    <<: *django
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=dev
    env_file:
      - .env
    ports: [ ]
    command: celery -A config worker --loglevel=info --queues=mcf_credits

#  celery-beat:
#    <<: *django
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - ENV=dev
#    command: bash -c "celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
#    ports: [ ]
#    depends_on:
#      - redis

  redis:
      image: redis
      ports:
          - "6379:6379"

volumes:
  postgres-data:
  static_volume: