# Generated by Django 4.2.24 on 2025-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_categor_a83c02_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_sales_3_011f53_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_rating_460c72_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="absolute_position",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="reviews_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales_30d",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sellers_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight_kg",
        ),
        migrations.AddField(
            model_name="product",
            name="article_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="article ID"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="merchant_name",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="merchant name"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_count",
            field=models.PositiveIntegerField(default=0, verbose_name="count"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_orders",
            field=models.PositiveIntegerField(default=0, verbose_name="product orders"),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="photo URL"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="catalog_pro_categor_7c1c1f_idx"
            ),
        ),
    ]
