# Generated by Django 4.2.24 on 2025-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["article_id"], name="catalog_pro_article_7b092b_idx"
            ),
        ),
    ]
