# Generated by Django 4.2.24 on 2025-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gmv",
            field=models.PositiveIntegerField(default=0, verbose_name="GMV"),
        ),
    ]
