# Generated by Django 4.2.24 on 2025-09-18 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Wrong phone_number format, "
                        "it should start with '+' sign and has 11 digits. "
                        "Example: '+77777777777'",
                        regex="^\\+[7]\\d{10}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
