# Generated by Django 4.2.24 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
