# Generated by Django 4.2.24 on 2025-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_status",
            field=models.CharField(
                choices=[("NOT_PAID", "Not paid"), ("PAID", "Paid")],
                default="NOT_PAID",
                max_length=20,
                verbose_name="payment status",
            ),
        ),
    ]
